set(CPACK_PACKAGE_INSTALL_DIRECTORY "$LOCALAPPDATA\\${CPACK_PACKAGE_NAME}")
set(CPACK_NSIS_TEMPLATE "${CMAKE_SOURCE_DIR}/installer/user_installer.nsi")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_UserSetup")
